### ISSUE TITLE
Blank row in spreadsheet breaks map

### ISSUE THREAD

**Issue by mapsandapps** [CivicTechAtlanta/mapsforus#7]
All rows after the blank one don't get displayed

**Comment by marktnoonan** [comment]
I have a kind of daft solution. Per Tabletop's docs, there is not a good way around this: 

> Empty rows are trouble. If you have a row that's completely empty, Google doesn't return any rows after the empty row. As a result, you need to make sure every line in your spreadsheet has data in it.

I grabbed a really simple auto-incrementing number script from here: https://blog.cloudstitch.com/auto-incrementing-id-columns-in-google-sheets-d9b31b2cc060 and altered it a little bit. Now when a row is edited (including the content being deleted) this script puts a space character in the A column of that row, if the A column is empty. Looks no different but Google will happily process the row and continue down through the sheet.

Here's my edited version of the script. I haven't renamed the variables etc. and I don't fully understand all the details inside the loop, but it is working for me!

`function onEdit() {

  var AUTOINC_COLUMN = 0;
  var HEADER_ROW_COUNT = 1;
  
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var worksheet   = spreadsheet.getSheetByName("Points");
  var rows        = worksheet.getDataRange().getNumRows();
  var vals        = worksheet.getSheetValues(1, 1, rows+1, 2);
  
  for (var row = HEADER_ROW_COUNT; row < vals.length; row++) {
    try {
      var id = vals[row][AUTOINC_COLUMN];
      Logger.log(id);Logger.log((""+id).length ===0);
      if ((""+id).length === 0) {
        // Here the columns & rows are 1-indexed
        worksheet.getRange(row+1, AUTOINC_COLUMN+1).setValue(" ");
      }
    } catch(ex) {
      // Keep calm and carry on
    }
  }
}`

**Comment by mapsandapps** [comment]
I like it, and it seems to work just fine! I added the script to the template google sheet, so all new maps should have this functionality by default. Thanks for helping out!
